name: Build openvas-smb

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    container: debian:stable-slim

    steps:
      - uses: .github/actions/install-dependencies-action@main
      - name: Configure and build
        run: |
          mkdir build && cd build/ && cmake -DCMAKE_BUILD_TYPE=Release .. && make install
