name: Build openvas-smb

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    container: debian:stable-slim

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: ./.github/actions/install-dependencies-action
      - name: Configure and build
        run: |
          mkdir build && cd build/ && cmake -DCMAKE_BUILD_TYPE=Release .. && make install
